### ISSUE TITLE
Saran Plugin GrabGan

### ISSUE THREAD

**Issue by alvindwiputra23** [FebriPratama/grabgan#1]
1. di gambar yang terisi hanya nama dan title, kurang bagian diskripsi gambar
   ![screenshot_16](https://cloud.githubusercontent.com/assets/14946721/10257380/2e111f16-6981-11e5-893d-477fba81ef86.png)
2. gambar hilang masih bisa ke grab
3. plugin tidak bisa di gunakan di semua theme wp, jadi hanya tertuntu. tp gk masalah . buat saran aj
4. kalau bisa di tambahkan, time posting seperti tanggal bulan tahun + jam, di plugin nya, biar bisa di set old and future time. set-nya manual aj.

Untuk sementara feb . . . tar kalau ada lagi tak kabari lagi. kalau udah kabari ane ya :D

**Comment by FebriPratama** [comment]
Fixed

**Comment by alvindwiputra23** [comment]
Mantab, Siap di coba kaka :D

On Fri, Oct 9, 2015 at 7:30 AM, Febri Arga Pratama <notifications@github.com
